image: inskale

stages:
  - deploy

deploy-develop:
  stage: deploy

  before_script:
    - git config --global user.email "yannick.wieland@hs-pforzheim.de"
    - git config --global user.name "Automated Release Development"
    - chmod +x ./Pyodide/Scripts/copyFiles.sh
    - apk add rsync
    - apk add zip


  script:
    - mkdir temp
    - cd temp/
    - git clone https://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@github.com/TheHowland/InskaLE.git .
    - git checkout $(git log --branches -1 --pretty=format:"%H")
    - echo "CopyFiles:"
    - ../Pyodide/Scripts/copyFiles.sh
    - echo "Configuration is:"
    - echo "$(<src/conf/conf.json )"
    - ls -a
    - cp ../Pyodide/index.html .
    - git add .
    - git commit -m "auto update dev release"
    - git push https://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@github.com/TheHowland/InskaLE.git HEAD:main

deploy-release:
  stage: deploy

  before_script:
  - git config --global user.email "yannick.wieland@hs-pforzheim.de"
  - git config --global user.name "Automated Release Deployment"
  - chmod +x ./Pyodide/Scripts/copyFiles.sh
  - chmod +x ./Pyodide/Scripts/clearFTPServer.sh
  - apk add rsync
  - apk add zip
  - apk add ncftp

  script:
    - mkdir temp
    - cd temp/
    - git clone https://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@github.com/prof-sky/inskale.git .
    - git checkout main
    - echo "CopyFiles:"
    - ../Pyodide/Scripts/copyFiles.sh
    - echo "Configuration is:"
    - echo "$(<src/conf/conf.json )"
    - ls -a
    # copy and upload maintanance index.html
    - cp ../Pyodide/Scripts/UpdateInProgress.html index.html
    - ncftpput -u f017019e -p EuVumvJ4TyqztDz7Qgwq -S .tmp ftp://w0182f79.kasserver.com/simplipfy / ./index.html
    - rm index.html
    - echo clear FTP server
    - ../Pyodide/Scripts/clearFTPServer.sh
    # upload all files to ftp server
    - ncftpput -u f017019e -p EuVumvJ4TyqztDz7Qgwq -R ftp://w0182f79.kasserver.com/simplipfy / ./
    # upload simpliPFy index.html (override maintenance index.html)
    - cp ../Pyodide/index.html .
    - sed -i "/setSiteId/s/'2'/'1'/" index.html
    - ncftpput -u f017019e -p EuVumvJ4TyqztDz7Qgwq -S .tmp ftp://w0182f79.kasserver.com/simplipfy / ./index.html
    # upload to github of prof-sky
    - sed -i "/setSiteId/s/'2'/'3'/" index.html
    - git add .
    - git commit -m "auto update release"
    - git push https://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@github.com/prof-sky/inskale.git

  rules:
    - if: $CI_COMMIT_BRANCH == "release"


