image: inskale

stages:
  - deploy

deploy-develop:
  stage: deploy

  before_script:
    - git config --global user.email "yannick.wieland@hs-pforzheim.de"
    - git config --global user.name "Automated Development Deployment"
    - chmod +x ./Pyodide/Scripts/copyFiles.sh
    - apk add rsync
    - apk add zip


  script:
    - mkdir temp
    - cd temp/
    - git clone https://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@github.com/TheHowland/InskaLE.git .
    - echo "Update config:"
    - rsync ../Pyodide/Configurations/conf-gitHubPageHowland.json ./src/resources/conf/conf-gitHubPageHowland.json
    - mv -f ./src/resources/conf/conf-gitHubPageHowland.json ./src/resources/conf/conf.json
    - ls -a
    - echo "CopyFiles:"
    - ../Pyodide/Scripts/copyFiles.sh
    - git add .
    - git commit -m "auto update release"
    - git push https://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@github.com/TheHowland/InskaLE.git

  # rules:
  #  - if: $CI_COMMIT_BRANCH == "main"

deploy-release:
  stage: deploy

  before_script:
  - git config --global user.email "yannick.wieland@hs-pforzheim.de"
  - git config --global user.name "Automated Release Deployment"
  - chmod +x ./Pyodide/Scripts/copyFiles.sh
  - apk add rsync
  - apk add zip

  script:
    - mkdir temp
    - cd temp/
    - git clone https://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@github.com/prof-sky/inskale.git .
    - echo "Update config:"
    - cp -rf ../Pyodide/Configurations/conf-gitHubPageProfSky.json ./src/resources/conf/conf.json
    - echo "CopyFiles:"
    - ../Pyodide/Scripts/copyFiles.sh
    - git add .
    - git commit -m "auto update release"
    - git push https://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@github.com/prof-sky/inskale.git

  rules:
    - if: $CI_COMMIT_BRANCH == "release"


