image: inskale

stages:
  - deploy

variables:
  FTP_SERVER: "w0182f79.kasserver.com"
  FTP_USER: "f017019e"
  FTP_PASS: "EuVumvJ4TyqztDz7Qgwq"
  FTP_FOLDER: /simplipfy
  FTP_SERVER_FULL_PATH: "ftp://w0182f79.kasserver.com/simplipfy"

deploy-develop:
  stage: deploy

  before_script:
    - git config --global user.email "yannick.wieland@hs-pforzheim.de"
    - git config --global user.name "Automated Release Development"
    - chmod +x ./Pyodide/Scripts/copyFiles.sh
    - chmod +x ./Pyodide/Scripts/generateSVGFiles.py
    - apk add rsync
    - apk add zip
    - apk add python3 py3-pip
    - lcapyPkgName=$(ls Pyodide/Packages | grep 'lcapy' | head -n 1)
    - schemdrawPkgName=$(ls Pyodide/Packages | grep 'schemdraw' | head -n 1)
    - pip3 install Pyodide/Packages/$lcapyPkgName
    - pip3 install Pyodide/Packages/$schemdrawPkgName


  script:
    - mkdir temp
    - cd temp/
    - git clone https://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@github.com/TheHowland/InskaLE.git .
    - git checkout $(git log --branches -1 --pretty=format:"%H")
    - echo "CopyFiles:"
    - ../Pyodide/Scripts/copyFiles.sh
    - echo "Configuration is:"
    - echo "$(<src/conf/conf.json )"
    - ls -a
    - python3 ../Pyodide/Scripts/generateSVGFiles.py
    - zip -r Circuits Circuits && rm -r Circuits/
    - git add .
    - git commit -m "auto update dev release"
    - git push https://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@github.com/TheHowland/InskaLE.git HEAD:main

  rules:
    - if: '$CI_COMMIT_BRANCH != "release"'


deploy-release:
  stage: deploy

  before_script:
  - git config --global user.email "yannick.wieland@hs-pforzheim.de"
  - git config --global user.name "Automated Release Deployment"
  - chmod +x ./Pyodide/Scripts/copyFiles.sh
  - chmod +x ./Pyodide/Scripts/clearFTPServer.sh
  - apk add rsync
  - apk add zip
  - apk add ncftp
  - apk add python3 py3-pip
  - lcapyPkgName=$(ls Pyodide/Packages | grep 'lcapy' | head -n 1)
  - schemdrawPkgName=$(ls Pyodide/Packages | grep 'schemdraw' | head -n 1)
  - pip3 install Pyodide/Packages/$lcapyPkgName
  - pip3 install Pyodide/Packages/$schemdrawPkgName

  script:
    - mkdir temp
    - cd temp/
    - git clone https://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@github.com/prof-sky/inskale.git .
    - git checkout main
    - echo "CopyFiles:"
    - ../Pyodide/Scripts/copyFiles.sh
    - echo "Configuration is:"
    - echo "$(<src/conf/conf.json )"
    - ls -a
    # generate svg files for circuit selector
    - python3 ../Pyodide/Scripts/generateSVGFiles.py
    - rm -rf __pycache__
    - zip -r Circuits Circuits && rm -r Circuits/
    # upload to github of prof-sky
    - sed -i /setSiteId/s/'2'/'3'/ ./src/scripts/utils/matomoHelper.js
    - git add .
    - git commit -m "auto update release"
    - git push https://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@github.com/prof-sky/inskale.git
    # copy and upload maintanance index.html
    - cp ../Pyodide/Scripts/UpdateInProgress.html index.html
    - ncftpput -u $FTP_USER -p $FTP_PASS -S .tmp $FTP_SERVER $FTP_FOLDER ./index.html
    - rm index.html
    - echo clear FTP server
    - ../Pyodide/Scripts/clearFTPServer.sh
    # remove files that should not be on simplipfy.org
    - rm -rf .git/
    - rm -rf .gitignore
    # upload all files to ftp server
    - sed -i /setSiteId/s/'3'/'1'/ ./src/scripts/utils/matomoHelper.js
    - cat ./src/scripts/utils/matomoHelper.js
    - ncftpput -u $FTP_USER -p $FTP_PASS -R $FTP_SERVER $FTP_FOLDER ./
    # upload simpliPFy index.html (override maintenance index.html)
    - cp ../Pyodide/index.html .
    - ncftpput -u $FTP_USER -p $FTP_PASS -S .tmp $FTP_SERVER $FTP_FOLDER ./index.html


  rules:
    - if: $CI_COMMIT_BRANCH == "release"


