dist: xenial
language: python
python:
  - 2.7
  - 3.5
  - 3.6
install:
  - pip install -r requirements.txt
script:
  - python -c "from lcapy import show_version; show_version()"
  - nosetests
notifications:
  email:
    on_success: never
    on_failure: always
    
