name: Run tests

on:
  push:

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.5, 3.6, 3.7, 3.8, 3.9]
    steps:
    - name: Check out
      uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install
      run: |
        pip install .
        pip install nose
        python -c "from lcapy import show_version; show_version()"
    - name: Run tests
      run: nosetests
